version: '3.1'
services:
  db:
    image: postgres
    restart: always
    ports:
        - "5432:5432"
    environment:
        POSTGRES_DB: schedule
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 12345

  redis:
    image: redis
    ports:
      - "6379:6379"

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOST=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=12345
    ports:
      - "8081:8081"
    depends_on:
      - redis
