name: Build project
on: [pull_request]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn

      - name: Lint
        run: yarn lint

      - name: Setup docker
        run: yarn dev:init

      - name: Run migrations
        run: yarn typeorm migration:run

      - name: Start application
        run: yarn start
