name: Build project
on: [pull_request]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
          cmd: lint
          cmd: dev:init
          cmd: typeorm migration:run
          cmd: start
